<?php
/**
 * @file
 * This is the main module file.
 */

 /**
 * Implements hook_help().
 */
function likepost_help($path, $arg) {

  if ($path == 'admin/help#likepost') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('This module allows the user to like posts in Drupal.') . '</p>';
    return $output;
  }
}

/**
* Implements hook_menu().
*/
function likepost_menu() {
	$items['likepost/like'] = array(
		'title' => 'Like',
		'page callback' => 'likepost_like',
		'access callback' => TRUE,
		'type' => MENU_SUGGESTED_ITEM,
		);
	return $items;
}


function likepost_like($nodeid) {
	$nodeid = (int)$nodeid;
	global $user;

	$like = likepost_get_like($nodeid, $user->uid);
	if ($like != 0) {
		db_delete('likepost_table_for_likes')
		->condition('userid', $user->uid)
		->condition('nodeid', $nodeid)
		->execute();
	} else {
		db_insert('likepost_table_for_likes')
		->fields(array(
		'userid' => $user->uid,
		'nodeid' => $nodeid
		))
		->execute();
	}


	$like = likepost_get_like($nodeid, $user->uid);
	$total_count = likepost_get_total_like($nodeid);
	drupal_json_output(array(
		'like_status' => $like,
		'total_count' => $total_count
		)
	);
	exit();


}

/**
* Return the total like count for a node.
*/
function likepost_get_total_like($nid) {
	$total_count = db_query('SELECT count(*) from {likepost_table_for_likes} where nodeid = :nodeid',
	array(':nodeid' => $nid))->fetchField();
	return $total_count;
}

/**
* Return the if the current user liked the node.
*/
function likepost_get_like($nodeid, $userid) {
	$like = db_query('SELECT count(*) FROM {likepost_table_for_likes} WHERE
	nodeid = :nodeid AND userid = :userid', array(':nodeid' => $nodeid, ':userid' => $userid))->fetchField();
	return $like;
}


/**
 * Implementation of hook_node_view
 */
function likepost_node_view($node, $view_mode) {
   if ($view_mode == 'full'){
    	$node->content['likepost_display'] =  array('#markup' => display_like_post_details($node->nid),'#weight' => 100);
    } 

}

/**
* Displays the Like post details.
*/
function display_like_post_details($nid) {

	drupal_add_js(drupal_get_path('module', 'likepost') .'/likepost.js');
	drupal_add_css(drupal_get_path('module', 'likepost') .'/likepost.css');	
	global $user;
	global $base_url;

	$totalLike =  likepost_get_total_like($nid);
	$hasCurrentUserLiked = likepost_get_like($nid , $user->uid);

	
	$output = '<div class="likepost">';
	$output .= 'Total number of likes on the post are ';
	$output .= '<div class="total_count">'.$totalLike.'</div>';
	$output .= '<a class ="like-link" href = "'.$base_url.'/likepost/like/'.$nid.'" >';
	if($hasCurrentUserLiked == 0) $output .= 'Like';
	else $output .= 'Delete Like';
	$output .= '</a>';
	$output .= '</div>'; 
	return $output;
}